config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'registrar', to: 'devise/registrations#new', as: :registrar
    get 'comenzar', to: 'devise/sessions#new', as: :comenzar
    get 'destruir', to: 'devise/sessions#destroy', as: :destruir
  end

  resources :statuses
  get 'timeline', to: 'statuses#index', as: :timeline
  root to: 'statuses#index'

  get '/:id', to: 'perfil#show'

end

app/models/status.rb
class Status < ActiveRecord::Base
		attr_accessible :contenido, :user_id
			belongs_to :user

		validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         attr_accessible :primer_nombre, :primer_apellido, :nickname, :password, :password_confirmation,
         				:email, :encrypted_password

        has_many :statuses

        validates :primer_nombre, presence: true
        validates :primer_apellido, presence: true
        validates :nickname, presence: true, 
        					 uniqueness: true#,
        					 #format: {
        					 	#with: /a-zA-Z0-9_-/,
                    #with: /a-zA-Z/,
        					 	#message: 'El nickname debe contener un formato adecuado (a-zA-Z0-9_-)'
        					 #}

        def nombre_completo
        	primer_nombre + " " + primer_apellido
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_paramters, if: :devise_controller?

  protected
  def configure_permitted_paramters
  	devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:primer_nombre, :primer_apellido, :nickname, :password, :password_confirmation, :email, :encrypted_password)}
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  #El filtro filter es para que no se pueda dar de alta estatus si no estas registrado
  before_filter :authenticate_user!, only: [:new]
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses}
      end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:user_id, :contenido)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
		#agregando metodos para comportamientos visuales
	def flash_class(type)
		case type
		when :alert
			"alert-danger"
		when :notice
			"alert-success"
		else
			""		
		end
	end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/_messagesLayout.html.erb
<% if flash[:notice]%>
	<div class="alert alert-info alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true" ><i class="fa fa-times"></i>x</button>
		<%= flash[:notice]%>
	</div>
<% end %>

<% if flash[:alert]%>
	<div class="alert alert-danger alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true" ><i class="fa fa-times"></i>x</button>
		<%= flash[:alert]%>
	</div>
<% end %>

<!-- esta madre no sirvio con ayuda del application_helper... revisar por qué....

!% flash.each do | type, message| %>
	<div class="alert <!%= flash_class type %> alert-dismissable">
    	 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    	 <!%= message %>
	</div>
<!% end %-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubinmz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
		<div class="navbar-inner">
			<div class="container-fluid">
				<%= link_to "RubinMz", root_path, :class => "navbar-brand"%>
				<ul class="nav navbar-nav">
					<li class="active"><%= link_to "Status", timeline_path %></li>
				</ul>
				<ul class="nav navbar-nav pull-right">
					<% if user_signed_in? %>
						<li><%= link_to current_user.nickname, edit_user_registration_path %></li>					
						<li><%= link_to "Cerrar sesión", destruir_path, method: :delete %></li>				
					<% else %>
						<li><%= link_to "Iniciar Sesión", comenzar_path %></li>				
						<li><%= link_to "Registrar", registrar_path %></li>				
					<% end %>
				</ul>
			</div>
		</div>
	</div>

	<div class="container-fluid">
	<row class="main-row col-md-9">
		<!--p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p-->
		<!-- Agregando mensajes flash -->

		<%= render "layouts/messagesLayout" %>
		<%= yield %>
	</row>
	</div>

</body>
</html>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.input :user_id, collection: User.all, label_method: :nombre_completo %>
  <%= f.input :contenido %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>Todos los estados</h1>
</div>

<%= link_to "Nuevo Estado", new_status_path, class: "btn btn-success" %>

<% @statuses.each do |status| %>
  <div class="status">
    <strong><%= status.user.nombre_completo %></strong> 
    <p><%= status.contenido %></p>
    <div>
      <%= link_to "Hace " + time_ago_in_words(status.created_at), status %> | 
      <%= link_to "Mostrar", status %>
      <span class="admin">
        <%= link_to "Editar", edit_status_path(status) %> |
        <%= link_to "Eliminar", status, method: :delete, data: {confirm: "Estás seguro que quieres borrar este estado"} %>
      </span>
    </div>
  </div>
<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Nombre:</strong>
  <%= @status.user.nombre_completo %>
</p>
<p>
  <strong>Contenido:</strong>
  <%= @status.contenido %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>